services:
  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      - ..:/app
      - node_modules:/app/frontend/node_modules
      - pnpm-store:/app/frontend/.pnpm-store
    ports:
      - 5173:5173
    entrypoint: ["pnpm","dev","--host"]
    restart: always
volumes:
  node_modules:
  pnpm-store:
