services:
  backend:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - ..:/app
    ports:
      - 8000:8000
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      MYSQL_SERVER: db
    restart: always
