services:
  backend:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - ..:/app
    ports:
      - 8000:8000
    entrypoint: ["uvicorn","main:app","--reload","--host","0.0.0.0","--port","8000"]
