services:
  server:
    image: nginx:latest
    ports:
      - 443:443
    tty: true
    volumes:
      - dist:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: always
  backend:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - ..:/app
    ports:
      - 8000:8000
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      - ..:/app
      - node_modules:/app/frontend/node_modules
      - pnpm-store:/app/frontend/.pnpm-store
      - dist:/app/frontend/dist
    entrypoint: ["pnpm", "build"]
volumes:
  dist:
  node_modules:
  pnpm-store:
